"use strict";
exports.__esModule = true;
var PlayerSkillsEntity = /** @class */ (function () {
    function PlayerSkillsEntity(_a) {
        var gk_diving = _a.gk_diving, gk_handling = _a.gk_handling, gk_kicking = _a.gk_kicking, gk_reflexes = _a.gk_reflexes, gk_speed = _a.gk_speed, gk_positioning = _a.gk_positioning, player_traits = _a.player_traits, attacking_crossing = _a.attacking_crossing, attacking_finishing = _a.attacking_finishing, attacking_heading_accuracy = _a.attacking_heading_accuracy, attacking_short_passing = _a.attacking_short_passing, attacking_volleys = _a.attacking_volleys, skill_dribbling = _a.skill_dribbling, skill_curve = _a.skill_curve, skill_fk_accuracy = _a.skill_fk_accuracy, skill_long_passing = _a.skill_long_passing, skill_ball_control = _a.skill_ball_control, movement_acceleration = _a.movement_acceleration, movement_sprint_speed = _a.movement_sprint_speed, movement_agility = _a.movement_agility, movement_reactions = _a.movement_reactions, movement_balance = _a.movement_balance, power_shot_power = _a.power_shot_power, power_jumping = _a.power_jumping, power_stamina = _a.power_stamina, power_strength = _a.power_strength, power_long_shots = _a.power_long_shots, mentality_aggression = _a.mentality_aggression, mentality_interceptions = _a.mentality_interceptions, mentality_positioning = _a.mentality_positioning, mentality_vision = _a.mentality_vision, mentality_penalties = _a.mentality_penalties, mentality_composure = _a.mentality_composure, defending_marking = _a.defending_marking, defending_standing_tackle = _a.defending_standing_tackle, defending_sliding_tackle = _a.defending_sliding_tackle, goalkeeping_diving = _a.goalkeeping_diving, goalkeeping_handling = _a.goalkeeping_handling, goalkeeping_kicking = _a.goalkeeping_kicking, goalkeeping_positioning = _a.goalkeeping_positioning, goalkeeping_reflexes = _a.goalkeeping_reflexes;
        this.gk_diving = gk_diving;
        this.gk_handling = gk_handling;
        this.gk_kicking = gk_kicking;
        this.gk_reflexes = gk_reflexes;
        this.gk_speed = gk_speed;
        this.gk_positioning = gk_positioning;
        this.player_traits = player_traits;
        this.attacking_crossing = attacking_crossing;
        this.attacking_finishing = attacking_finishing;
        this.attacking_heading_accuracy = attacking_heading_accuracy;
        this.attacking_short_passing = attacking_short_passing;
        this.attacking_volleys = attacking_volleys;
        this.skill_dribbling = skill_dribbling;
        this.skill_curve = skill_curve;
        this.skill_fk_accuracy = skill_fk_accuracy;
        this.skill_long_passing = skill_long_passing;
        this.skill_ball_control = skill_ball_control;
        this.movement_acceleration = movement_acceleration;
        this.movement_sprint_speed = movement_sprint_speed;
        this.movement_agility = movement_agility;
        this.movement_reactions = movement_reactions;
        this.movement_balance = movement_balance;
        this.power_shot_power = power_shot_power;
        this.power_jumping = power_jumping;
        this.power_stamina = power_stamina;
        this.power_strength = power_strength;
        this.power_long_shots = power_long_shots;
        this.mentality_aggression = mentality_aggression;
        this.mentality_interceptions = mentality_interceptions;
        this.mentality_positioning = mentality_positioning;
        this.mentality_vision = mentality_vision;
        this.mentality_penalties = mentality_penalties;
        this.mentality_composure = mentality_composure;
        this.defending_marking = defending_marking;
        this.defending_standing_tackle = defending_standing_tackle;
        this.defending_sliding_tackle = defending_sliding_tackle;
        this.goalkeeping_diving = goalkeeping_diving;
        this.goalkeeping_handling = goalkeeping_handling;
        this.goalkeeping_kicking = goalkeeping_kicking;
        this.goalkeeping_positioning = goalkeeping_positioning;
        this.goalkeeping_reflexes = goalkeeping_reflexes;
    }
    return PlayerSkillsEntity;
}());
exports["default"] = PlayerSkillsEntity;
